### ISSUE TITLE
#error “SSE2 instruction set not enabled”

### ISSUE THREAD

**Issue by makson96** [xythobuz/OpenRaider#5]
The OpenRaider is vulnerable to this error:
https://stackoverflow.com/questions/16410149/error-sse2-instruction-set-not-enabled-when-including-emmintrin-h
Please add appropriate cxx flags in CMakeLists.txt to make it build easily on 32bit systems.

**Comment by xythobuz** [comment]
OpenRaider is not using SSE or emmintrin.h anywhere. Does this still apply in this case? Do you have a build-log showing this problem?

**Comment by makson96** [comment]
Here you are:
https://launchpadlibrarian.net/200526479/buildlog_ubuntu-trusty-i386.openraider_0.1.4%2Bgit20150317-trusty6_BUILDING.txt.gz

In file included from /build/buildd/openraider-0.1.4+git20150317/src/deps/stb/stb_image.h:624:0, from /build/buildd/openraider-0.1.4+git20150317/src/deps/stb/stb.cpp:12: /usr/lib/gcc/i686-linux-gnu/4.8/include/emmintrin.h:31:3: error: #error "SSE2 instruction set not enabled" # error "SSE2 instruction set not enabled"

**Comment by xythobuz** [comment]
Ahh, so it's stb_image. Will investigate...
