### ISSUE TITLE
Menu.cpp:88:38: error

### ISSUE THREAD

**Issue by makson96** [xythobuz/OpenRaider#6]
During compilation on Linux I get error:
```
Menu.cpp:88:38: error: conversion from 'glm::i32vec2 {aka glm::detail::tvec2<int, (glm::precision)0u>}' to non-scalar type 'glm::vec2 {aka glm::detail::tvec2<float, (glm::precision)0u>}' requested
```

Could you please take a look at it.
Full details:
https://launchpadlibrarian.net/200529703/buildlog_ubuntu-trusty-i386.openraider_0.1.4%2Bgit20150317-trusty8_BUILDING.txt.gz

**Comment by xythobuz** [comment]
The version of glm you are using is too old! Take a look at the [Readme](https://github.com/xythobuz/OpenRaider/blob/master/README.md#dependencies), you need at least version 0.9.6. Installing glm from source is [very easy](https://github.com/xythobuz/OpenRaider/blob/master/cmake/travis_install_linux.sh#L10-L12), however...
